export const restaurants = [
  {
    id: 1,
    name: "Spice Garden",
    cuisines: ["Indian", "North Indian", "Tandoori"],
    location: "Hyderabad, Telangana",
    rating: 4.3,
    imageUrl: "https://images.unsplash.com/photo-1600628422019-4c5f3f6b3f6a",
  },
  {
    id: 2,
    name: "Ocean Breeze Café",
    cuisines: ["Continental", "Seafood"],
    location: "Vizag, Andhra Pradesh",
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c",
  },
  {
    id: 3,
    name: "Dragon Hut",
    cuisines: ["Chinese", "Asian"],
    location: "Bengaluru, Karnataka",
    rating: 4.2,
    imageUrl: "https://images.unsplash.com/photo-1541542684-4d6e0c9fba84",
  },
  {
    id: 4,
    name: "Burger Hub",
    cuisines: ["Fast Food", "Burgers"],
    location: "Mumbai, Maharashtra",
    rating: 4.0,
    imageUrl: "https://images.unsplash.com/photo-1550547660-d9450f859349",
  },
  {
    id: 5,
    name: "Royal Biryani House",
    cuisines: ["Indian", "Biryani"],
    location: "Chennai, Tamil Nadu",
    rating: 4.6,
    imageUrl: "https://images.unsplash.com/photo-1631515242808-497c3fbd3972",
  },
  {
    id: 6,
    name: "La Pasta Street",
    cuisines: ["Italian", "Pasta", "Pizza"],
    location: "Pune, Maharashtra",
    rating: 4.4,
    imageUrl: "https://images.unsplash.com/photo-1521389508051-d7ffb5dc8a40",
  },
  {
    id: 7,
    name: "Sushi Express",
    cuisines: ["Japanese", "Sushi"],
    location: "Delhi",
    rating: 4.1,
    imageUrl: "https://images.unsplash.com/photo-1553621042-f6e147245754",
  },
  {
    id: 8,
    name: "Green Leaf Vegan Café",
    cuisines: ["Vegan", "Healthy Food"],
    location: "Kolkata, West Bengal",
    rating: 4.7,
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999",
  },
  {
    id: 9,
    name: "Taco Fiesta",
    cuisines: ["Mexican"],
    location: "Goa",
    rating: 4.0,
    imageUrl: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56",
  },
  {
    id: 10,
    name: "BBQ Central",
    cuisines: ["Barbecue", "Grill", "American"],
    location: "Ahmedabad, Gujarat",
    rating: 4.5,
    imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1",
  },
];
